### ISSUE TITLE
Where is this stuff documented?

### ISSUE THREAD

**Issue by geajack** [isometimes/rpi4-osdev#42]
Hi, I'm loving this tutorial! But I find myself wondering how I could have figured any of this out without a tutorial. Where did you get all this information? I mean things about the fundamental protocols you have to keep to to run code on the Pi 4. Like that the file has to be called `kernel8.img`, how the SD card has to be formatted, or like the actual format that the `.img` file should have (i.e. how to put the linker script together, the correct `objcopy` commands, etc).

Is this stuff even documented officially *anywhere*? All I can find are forum posts linking to more forum posts with shreds of information.

**Comment by isometimes** [comment]
Hi,

I'm afraid much of this tutorial is pieced together from the official Raspberry Pi/ARM documentation (linked from the tutorial text) or indeed from many forum/blog posts I found along the way. The tutorial actually started because I needed to record all the information I was finding out so I didn't lose track of why I made certain decisions. It was a product of a lot of Google searches!

Sorry that the answer isn't a more pleasant one!

Adam
