### ISSUE TITLE
"Incorrect" mailbox protocol in part 5

### ISSUE THREAD

**Issue by geajack** [isometimes/rpi4-osdev#43]
In [part 5](https://www.rpi4os.com/part5-framebuffer/), you implement the mailbox protocol which is "documented" [here](https://github.com/raspberrypi/firmware/wiki/Accessing-mailboxes). Your function `mbox_call()` is basically a C implementation of the algorithm described in that document:

> 1. Read the status register until the empty flag is not set
> 2. Read data from the read register
> 3. If the lower four bits do not match the channel number desired then repeat from 1
> 4. The upper 28 bits are the returned data

The relevant part of your code is:

```c
while (1) {
    while (mmio_read(MBOX_STATUS) & MBOX_EMPTY);
    if (r == mmio_read(MBOX_READ))
        return mbox[1]==MBOX_RESPONSE;
}
```

However, you can see that that if statement does not quite match step (3). Instead of just checking if the channel number matches the value of the read register, we check if the whole thing matches our entire message (28 bits of address + 4 bits of channel).

What justifies this?

**Comment by isometimes** [comment]
Hi,

Thanks for this. The response message always overwrites the request message (Ref: https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface) and so you can assume that the buffer address will be the same. Therefore it's legitimate to compare all 32 bits rather than just the 4 bit channel number. In fact, it's better because you know that the response is to your specific message.

Hope that helps!
Adam
